system:
  env:
    python_deepmasc    : /lustre1/home/senda-em/.conda/envs/DeepMASC/bin/python
    python_cryoem_tools: /lustre1/home/senda-em/.conda/envs/cspa/bin/python

  toolbox:
    python:
      path: /lustre1/home/senda-em/.conda/envs/cspa/bin/python
      
    relion_image_handler:
      path: /lustre1/emsystem/apps/relion-5.0.0/bin/relion_image_handler

    deepmasc_contour: 
      env : python_deepmasc
      path: /lustre1/home/senda-em/emdata_senda-em/apps/DeepMASC/contour.py

    size_estimation: 
      env : python_cryoem_tools
      path: /lustre1/home/senda-em/emdata_senda-em/apps/cryoem_tools/src/spa/analyses/size_estimation.py
    
    negative_estimation: 
      env : python_cryoem_tools
      path: /lustre1/home/senda-em/emdata_senda-em/apps/cryoem_tools/src/spa/analyses/negative_density.py

    volume_alignment: 
      env : python_cryoem_tools
      path: /lustre1/home/senda-em/emdata_senda-em/apps/cryoem_tools/src/spa/analyses/volume_alignment.py

    boxsize_analysis:
      env : python_cryoem_tools
      path: /lustre1/home/senda-em/emdata_senda-em/apps/cryoem_tools/src/spa/analyses/boxsize_analysis.py

    binning_parameters:
      env: python_cryoem_tools
      path: /lustre1/home/senda-em/emdata_senda-em/apps/cryoem_tools/src/spa/analyses/binning_parameters.py

    extract_boxes:
      env: python_cryoem_tools
      path: /lustre1/home/senda-em/emdata_senda-em/apps/cryoem_tools/src/spa/analyses/compute_extraction_boxes.py
